import { PrismaClient, CommissionMode, LoanStatus, InstallmentStatus } from '@prisma/client';

const prisma = new PrismaClient();

// Strategy interface for commission calculation
export interface CommissionStrategy {
  calculateInstallmentCommission(
    installment: {
      interest: number;
      paidAmount: number;
      amount: number;
      number: number;
      principal: number;
    },
    totalInstallments: number,
    percentage: number,
    capitalRecoveredSoFar: number,
    totalPrincipal: number
  ): {
    commission: number;
    newCapitalRecovered: number;
  };
}

// Proportional Strategy: commission = interest_collected × percentage
// interest_collected = interest × min(paidAmount/amount, 1)
export class ProportionalStrategy implements CommissionStrategy {
  calculateInstallmentCommission(
    installment: { interest: number; paidAmount: number; amount: number; number: number; principal: number },
    _totalInstallments: number,
    percentage: number,
    capitalRecoveredSoFar: number,
    _totalPrincipal: number
  ): { commission: number; newCapitalRecovered: number } {
    const paymentRatio = Math.min(installment.paidAmount / installment.amount, 1);
    const interestCollected = installment.interest * paymentRatio;
    const commission = Math.round(interestCollected * (percentage / 100) * 100) / 100;
    const principalPaid = installment.principal * paymentRatio;
    
    return {
      commission,
      newCapitalRecovered: capitalRecoveredSoFar + principalPaid,
    };
  }
}

// After Capital Recovery Strategy: commission only after total collected >= loan principal.
// Tracks total amount paid (principal + interest), not just principal.
// Formula from spec: gananciaReal = max(0, totalCobrado - capitalPrestado)
//                    comisionGenerada = gananciaReal × %
export class AfterCapitalRecoveryStrategy implements CommissionStrategy {
  calculateInstallmentCommission(
    installment: { interest: number; paidAmount: number; amount: number; number: number; principal: number },
    _totalInstallments: number,
    percentage: number,
    capitalRecoveredSoFar: number,  // Actually: totalCollected so far (renamed for interface compatibility)
    totalPrincipal: number
  ): { commission: number; newCapitalRecovered: number } {
    const paymentRatio = Math.min(installment.paidAmount / installment.amount, 1);
    const amountPaid = installment.amount * paymentRatio;
    const totalCollected = capitalRecoveredSoFar + amountPaid;
    
    // gananciaReal = max(0, totalCobrado - capitalPrestado)
    const gananciaReal = Math.max(0, totalCollected - totalPrincipal);
    
    // Commission = gananciaReal × %, but only the portion generated by this installment
    // (avoid double-counting previous installments' gananciaReal)
    const gananciaPrevia = Math.max(0, capitalRecoveredSoFar - totalPrincipal);
    const gananciaDeEstaCuota = gananciaReal - gananciaPrevia;
    const commission = Math.round(gananciaDeEstaCuota * (percentage / 100) * 100) / 100;
    
    return {
      commission,
      newCapitalRecovered: Math.round(totalCollected * 100) / 100,
    };
  }
}

// Advanced Strategy: linear decay weight on commission
// weight = 1 - (i-1)/(n-1), early installments weighted more
export class AdvancedStrategy implements CommissionStrategy {
  calculateInstallmentCommission(
    installment: { interest: number; paidAmount: number; amount: number; number: number },
    _totalInstallments: number,
    percentage: number,
    capitalRecoveredSoFar: number,
    _totalPrincipal: number
  ): { commission: number; newCapitalRecovered: number } {
    // ADVANCED mode: full commission is considered generated from loan start.
    // Commission is calculated on total projected interest, independent of collection progress.
    const commission = Math.round(installment.interest * (percentage / 100) * 100) / 100;
    
    return {
      commission,
      newCapitalRecovered: capitalRecoveredSoFar,
    };
  }
}

// Strategy factory
export function getStrategy(mode: CommissionMode): CommissionStrategy {
  switch (mode) {
    case CommissionMode.AFTER_CAPITAL_RECOVERY:
      return new AfterCapitalRecoveryStrategy();
    case CommissionMode.ADVANCED:
      return new AdvancedStrategy();
    case CommissionMode.PROPORTIONAL:
    default:
      return new ProportionalStrategy();
  }
}

export interface LoanWithInstallments {
  id: string;
  assignedVendorId: string | null;
  commissionPercentage: number | null;
  commissionMode: CommissionMode | null;
  status: LoanStatus;
  amount: number;
  installments: Array<{
    interest: number;
    paidAmount: number;
    amount: number;
    number: number;
    status: InstallmentStatus;
    principal: number;
    interestCollected: number;
  }>;
}

export class CommissionService {
  /**
   * Project commission at loan creation time
   * Uses total interest from amortization to estimate commission
   */
  static projectCommission(
    principal: number,
    _annualInterestRate: number,
    termMonths: number,
    commissionPercentage: number,
    mode: CommissionMode,
    installmentAmount: number
  ): number {
    // Calculate total interest based on the loan terms
    // For simplicity, we use a simplified calculation
    // totalPayment = installmentAmount × termMonths
    // totalInterest = totalPayment - principal
    const totalPayment = installmentAmount * termMonths;
    const totalInterest = totalPayment - principal;
    
    if (totalInterest <= 0) {
      return 0;
    }
    
    const percentage = commissionPercentage / 100;
    
    switch (mode) {
      case CommissionMode.PROPORTIONAL:
        // Projected = totalInterest × percentage
        return Math.round(totalInterest * percentage * 100) / 100;
        
      case CommissionMode.AFTER_CAPITAL_RECOVERY:
        // For projection, assume capital will be recovered evenly
        // Commission only on interest after capital is recovered
        // Simplified: use proportional as approximation
        return Math.round(totalInterest * percentage * 100) / 100;
        
      case CommissionMode.ADVANCED:
        // For ADVANCED, projected = totalInterest × percentage
        // (actual distribution happens during recalculation)
        return Math.round(totalInterest * percentage * 100) / 100;
        
      default:
        return Math.round(totalInterest * percentage * 100) / 100;
    }
  }

  /**
   * Recalculate commission for a loan
   * Fetches loan with installments, calculates commission based on mode
   * Idempotent: always recalculates from scratch using current installment states
   */
  static async recalculateLoan(loanId: string): Promise<number | null> {
    const loan = await prisma.loan.findUnique({
      where: { id: loanId },
      include: {
        installments: {
          orderBy: { installmentNumber: 'asc' },
        },
        payments: {
          where: { status: 'COMPLETED' },
          select: { amount: true, installmentId: true, notes: true },
        },
      },
    }) as (LoanWithInstallments & { payments?: Array<{ amount: number; installmentId: string | null; notes: string | null }> }) | null;
    
    if (!loan) {
      return null;
    }
    
    // Skip if no seller assigned or no commission percentage set
    if (!loan.assignedVendorId || loan.commissionPercentage === null) {
      return null;
    }

    // PENDING loans: no commission generated (not approved/disbursed yet)
    if (loan.status === 'PENDING') {
      await prisma.loan.update({
        where: { id: loanId },
        data: { commissionGenerated: 0 },
      });
      return 0;
    }
    
    const mode = loan.commissionMode ?? CommissionMode.PROPORTIONAL;
    const percentage = loan.commissionPercentage;
    const strategy = getStrategy(mode);
    
    // Get only paid or partially paid installments for commission calculation
    // Calculate projected commission first (based on ALL installments)
    const totalInterest = loan.installments.reduce(
      (sum, inst) => sum + Number(inst.interest), 0
    );
    const projectedCommission = Math.round(totalInterest * (percentage / 100) * 100) / 100;

    // ADVANCED mode: full commission from start (unless PAID, REFINANCIADO or DEFAULTED — use actual collection)
    if (mode === 'ADVANCED' && loan.status !== 'PAID' && loan.status !== 'REFINANCIADO' && loan.status !== 'DEFAULTED') {
      // Rule 1: include actual interest collected from INTEREST_ONLY cuotas (regla 1)
      // ADVANCED charges commission upfront on total projected interest, but if the loan
      // had real interest-only payments, those are real interest and must be counted too.
      // The strategy itself only iterates non-PENDING cuotas and uses paidAmount; for
      // INTEREST_ONLY cuotas the interest is in interestCollected, not paidAmount.
      // Since projectedCommission already covers full project interest, we add only the
      // delta — but in practice the projected commission doesn't include interest that was
      // paid early via INTEREST_ONLY before the loan started being current. Simplest correct
      // approach: projected commission = max(projected, sum of interestCollected × %).
      const interestOnlySum = loan.installments
        .filter(i => i.status === 'INTEREST_ONLY' && Number(i.interestCollected) > 0)
        .reduce((sum, i) => sum + Number(i.interestCollected), 0);
      const interestOnlyCommission = Math.round(interestOnlySum * (percentage / 100) * 100) / 100;
      const finalProjected = Math.max(projectedCommission, interestOnlyCommission);

      await prisma.loan.update({
        where: { id: loanId },
        data: {
          commissionGenerated: finalProjected,
          commissionProjected: finalProjected,
        },
      });
      return finalProjected;
    }

    // Get only paid or partially paid installments for commission calculation
    // Exclude PENDING (not paid yet). Include PAID, PARTIAL, OVERDUE, and CANCELADA_POR_REFINANCIACION
    // (refinanced installments had real payments before refinancing — they count)
    // Get installments with real payments for commission calculation
    // For PAID/REFINANCIADO: only count installments that actually had payments (paidAmount > 0)
    // For active loans: exclude PENDING (not paid yet), include all others
    const isFinalStatus = loan.status === 'PAID' || loan.status === 'REFINANCIADO' || loan.status === 'DEFAULTED';
    const totalPrincipal = Number(loan.amount);

    // For PAID/REFINANCIADO/DEFAULTED: commission based on real profit + interest-only
    if (isFinalStatus) {
      // Filter out "Pago excepcional por refinanciación" — that payment is solely to
      // reduce the new loan's capital, not vendor commission. It must not inflate the
      // commission base on the refinanced loan.
      const isRefiExcepcional = (notes: string | null | undefined) =>
        (notes || '').includes('excepcional') || (notes || '').includes('reduce nuevo capital');

      const allPayments = (loan.payments || []).filter(
        (p) => !isRefiExcepcional(p.notes)
      );

      // REFINANCIADO: always compute as proportional (proporcional + interestOnly + mora),
      // independent of the original loan's commission mode and independent of gananciaReal.
      // DEFAULTED and PAID: behave as pure AFTER_CAPITAL_RECOVERY — gananciaReal × %,
      // no fallback. $0 if no real profit.
      let finalCommission = 0;
      if (loan.status === 'REFINANCIADO') {
        // Proportional on paid installments (PAID/PARTIAL/CANCELADA) using paidAmount
        const paidInstallments = loan.installments.filter(
          (inst) => inst.status !== 'PENDING' && inst.status !== 'INTEREST_ONLY' && Number(inst.paidAmount) > 0
        );
        let proporcionalCommission = 0;
        for (const inst of paidInstallments) {
          const interestCollected = Number(inst.interest) * Math.min(Number(inst.paidAmount) / Number(inst.amount), 1);
          proporcionalCommission += Math.round(interestCollected * (percentage / 100) * 100) / 100;
        }

        // Rule 1: INTEREST_ONLY cuotas contribue via interestCollected
        let interestOnlyCommission = 0;
        for (const inst of loan.installments) {
          if (inst.status === 'INTEREST_ONLY' && Number(inst.interestCollected) > 0) {
            interestOnlyCommission += Math.round(Number(inst.interestCollected) * (percentage / 100) * 100) / 100;
          }
        }

        // Mora payments (excluding capitalExtra/reduce nuevo capital — filtered above)
        let moraCommission = 0;
        for (const p of allPayments) {
          if (!p.installmentId && Number(p.amount) > 0 && (p.notes || '').includes('Mora')) {
            moraCommission += Math.round(Number(p.amount) * (percentage / 100) * 100) / 100;
          }
        }

        finalCommission = Math.round((proporcionalCommission + interestOnlyCommission + moraCommission) * 100) / 100;
      } else {
        // DEFAULTED / PAID: strict gananciaReal × %
        const totalPayments = allPayments.reduce((sum, p) => sum + Number(p.amount), 0);
        const gananciaReal = Math.max(0, totalPayments - totalPrincipal);
        finalCommission = Math.round(gananciaReal * (percentage / 100) * 100) / 100;
      }

      await prisma.loan.update({
        where: { id: loanId },
        data: {
          commissionGenerated: finalCommission,
          commissionProjected: finalCommission, // Closed loan: projected = generated
        },
      });
      return finalCommission;
    }

    // For active loans: per-installment calculation
    // Get only paid or partially paid installments (exclude PENDING)
    const activeInstallments = loan.installments.filter(
      (inst) => inst.status !== 'PENDING'
    );

    if (activeInstallments.length === 0) {
      await prisma.loan.update({
        where: { id: loanId },
        data: {
          commissionGenerated: 0,
          commissionProjected: projectedCommission,
        },
      });
      return 0;
    }

    // Separate INTEREST_ONLY from other installments: their interest is tracked
    // separately via interestCollected (rule 1) and not via paidAmount.
    const interestOnlyInstallments = activeInstallments.filter(
      (inst) => inst.status === 'INTEREST_ONLY' && Number(inst.interestCollected) > 0
    );
    const normalInstallments = activeInstallments.filter(
      (inst) => inst.status !== 'INTEREST_ONLY'
    );

    // Calculate commission using strategy on normal installments
    let totalCommission = 0;
    // For AFTER_CAPITAL_RECOVERY, the strategy's "capitalRecoveredSoFar" is actually
    // "totalCollected so far". Standalone payments (abono a cuenta, installmentId=null)
    // — which are how INTEREST_ONLY payments are recorded — are NOT represented in any
    // cuota's amountPaid, so we must seed the running total with them. Without this,
    // a loan with $200k capital and $212k collected (all INTEREST_ONLY + 1 PAID cuota
    // that recovered the capital partially) shows $0 commission even though there's $12k
    // of real profit to be commissionable.
    let capitalRecoveredSoFar = 0;
    if (mode === CommissionMode.AFTER_CAPITAL_RECOVERY) {
      const allPayments = loan.payments || [];
      capitalRecoveredSoFar = allPayments
        .filter((p) => !p.installmentId && Number(p.amount) > 0)
        .reduce((sum, p) => sum + Number(p.amount), 0);
    }

    for (const installment of normalInstallments) {
      const result = strategy.calculateInstallmentCommission(
        {
          interest: Number(installment.interest),
          paidAmount: Number(installment.paidAmount),
          amount: Number(installment.amount),
          number: installment.number,
          principal: Number(installment.principal),
        },
        loan.installments.length,
        percentage,
        capitalRecoveredSoFar,
        totalPrincipal
      );

      totalCommission += result.commission;
      capitalRecoveredSoFar = result.newCapitalRecovered;
    }

    // Rule 1 (refined): add commission for INTEREST_ONLY installments on ACTIVE loans
    // ONLY for modes that don't gate commission on capital recovery. For AFTER_CAPITAL_RECOVERY
    // the standalone interest-only payments are already counted via capitalRecoveredSoFar
    // (seeded above), which is the correct input for the strategy's gananciaReal calc.
    if (mode !== CommissionMode.AFTER_CAPITAL_RECOVERY) {
      for (const inst of interestOnlyInstallments) {
        const instCommission = Math.round(Number(inst.interestCollected) * (percentage / 100) * 100) / 100;
        totalCommission += instCommission;
        // NOTE: capital recovered stays as the strategy computed it — the principal of
        // INTEREST_ONLY was deferred, not paid, so it must not increment capitalRecoveredSoFar.
      }
    }

    // Round to 2 decimal places
    totalCommission = Math.round(totalCommission * 100) / 100;

    // Update loan with calculated commission
    await prisma.loan.update({
      where: { id: loanId },
      data: {
        commissionGenerated: totalCommission,
        commissionProjected: projectedCommission,
      },
    });
    
    return totalCommission;
  }

  /**
   * Recalculate commissions for all loans of a vendor
   */
  static async recalculateVendorLoans(vendorId: string): Promise<number> {
    const loans = await prisma.loan.findMany({
      where: {
        assignedVendorId: vendorId,
        status: { in: [LoanStatus.ACTIVE, LoanStatus.PENDING, LoanStatus.DEFAULTED] },
      },
    });
    
    let updatedCount = 0;
    for (const loan of loans) {
      const result = await CommissionService.recalculateLoan(loan.id);
      if (result !== null) {
        updatedCount++;
      }
    }
    
    return updatedCount;
  }
}

export default CommissionService;
